version: 0.2
artifacts:
  secondary-artifacts:
    GlueEtlArtifact:
      base-directory: glue
      files:
      - "**/*"
      discard-paths: yes
    GraphQLArtifact:
      base-directory: graphql
      files:
      - "**/*"
      discard-paths: yes
