AWSTemplateFormatVersion: "2010-09-09"
Description: Invoc
Parameters:
  PipelineBucket:
    Type: String
Outputs:
  RawS3Bucket:
    Value: !Ref GraphQLApiKey
  GraphQLUrl:
    Value: !GetAtt GraphQLApi.GraphQLUrl
  GraphQLApiKey:
    Value: !GetAtt GraphQLApiKey.ApiKey

Resources:
##########################################################
#  DB
##########################################################
  TableConsumptionDaily:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: consumption_daily
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: tenant
          AttributeType: N
        - AttributeName: date
          AttributeType: N
      KeySchema:
        - AttributeName: tenant
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE

##########################################################
#  S3
##########################################################
  S3GentrackTrialRaw:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain

##########################################################
#  Glue
##########################################################
  GlueEtl:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${PipelineBucket}/glue_etl.py"
      DefaultArguments:
        "--tenant": "1"
        "--s3_path": !Sub "s3://${S3GentrackTrialRaw}/"
      MaxCapacity: 2
      MaxRetries: 0
      Name: gentrack_etl
      Role: !Ref GlueRole

##########################################################
#  AppSync
##########################################################
  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: gentrack_graph_ql
      AuthenticationType: "API_KEY"

  GraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      DefinitionS3Location: !Sub "s3://${PipelineBucket}/schema.graphql"

  GraphQLApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !Ref GraphQLApi
      Expires: 365

  GraphQLConsumptionDailyDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref GraphQLApi
      Name: consumption_daily
      Type: "AMAZON_DYNAMODB"
      ServiceRoleArn: !Ref AppSyncRole
      DynamoDBConfig:
        TableName: !Ref TableConsumptionDaily
        AwsRegion: !Ref AWS::Region

  GraphQLListConsumptionDailyResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref GraphQLApi
      DataSourceName: !Ref GraphQLConsumptionDailyDataSource
      FieldName: "listConsumptionDaily(...): ConsumptionDailyConnection"
      RequestMappingTemplateS3Location: !Sub "s3://${PipelineBucket}/resolver_list_consumption_daily_request.vm"
      ResponseMappingTemplateS3Location: !Sub "s3://${PipelineBucket}/resolver_list_consumption_daily_response.vm"
      TypeName: Query

##########################################################
#  Role
##########################################################
  GlueRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: glue
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: glue.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess #TODO: Reduce permissions

  AppSyncRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: appsync
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: glue.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess #TODO: Reduce permissions
